routes/data_analysis.py
from flask import Blueprint, request, render_template, redirect, url_for, session
import json
import numpy as np
import pandas as pd
from utils.data_reading import load_guest_data, load_dictionary_data, process_expenses, process_settlement, \
    total_guests, guests_by_column, calculate_settlement
from utils.helpers import store_filter_data, store_mode_data
from utils.data_mapping import month_mapping, month_words, month_numbers, colours
from datetime import datetime, timedelta

import matplotlib.pyplot as plt
import plotly.graph_objects as go
from plotly.utils import PlotlyJSONEncoder
import plotly.express as px
from plotly.subplots import make_subplots
import calendar
from PIL import Image, ImageDraw, ImageOps, ImageEnhance, ImageFont
from utils.charts import DataChartCreator
import base64

data_analysis_bp = Blueprint('data_analysis', __name__, template_folder='templates')


class MakeDashboard:

    @staticmethod
    @data_analysis_bp.route('/')
    def dashboard():
        # Load guest data (you can replace this with the actual loading function)
        current_module = 'dashboard'

        # Retrieve year and month from the session
        filter_data = session.get('filter', {})
        year = filter_data.get('year')
        month = filter_data.get('month')

        df_guest = load_guest_data()

        if year and month:
            df_guest = total_guests(df_guest, year, month)

        month_name = month_mapping.get(month, None)  # Get the month name; default to None if not found

        if month_name:
            expenses_dict, monthname_year = load_dictionary_data('expenses', year, month)
            df_expenses = process_expenses(expenses_dict)
        else:
            expenses_dict, monthname_year = load_dictionary_data('expenses')
            df_expenses = process_expenses(expenses_dict)

        mode_data = session.get('mode', {})
        mode = mode_data.get('mode')

        if 'mode' not in mode_data:
            session['mode'] = {'mode': mode}

        chart_creator = DataChartCreator(df_guest, df_expenses, year, month, mode)
        graph_json = chart_creator.create_chart()

        return render_template("data_analysis.html", graph_json=graph_json, current_module=current_module)

    @staticmethod
    @data_analysis_bp.route('/filter_dashboard', methods=['POST'])
    def filter_dashboard():
        current_module = 'dashboard'

        # Retrieve the selected month and year from the form and save
        year, month = str(request.form['year']), str(request.form['month'])
        session['filter'] = {'year': year, 'month': month}

        mode_data = session.get('mode', {})
        mode = mode_data.get('mode', 'accounting')

        if 'mode' not in mode_data:
            session['mode'] = {'mode': mode}

        df_guest = load_guest_data()
        df_guest = total_guests(df_guest, year, month)

        month_name = month_mapping.get(month, None)  # Get the month name; default to None if not found

        if month_name:
            expenses_dict, monthname_year = load_dictionary_data('expenses', year, month)
            df_expenses = process_expenses(expenses_dict)
        else:
            expenses_dict, monthname_year = load_dictionary_data('expenses')
            df_expenses = process_expenses(expenses_dict)

        chart_creator = DataChartCreator(df_guest, df_expenses, year, month, mode)
        graph_json = chart_creator.create_chart()

        return render_template('data_analysis.html', year=year, month=month, tables=[df_guest], graph_json=graph_json,
                               current_module=current_module)

    @staticmethod
    @data_analysis_bp.route('/dashboard_mode', methods=['POST'])
    def dashboard_mode():
        current_module = 'dashboard'

        mode = request.form.get('mode', 'accounting')  # Default to accounting

        store_mode_data(mode)

        # Get year, month, and mode from the query parameters (no need to save it in session here!)
        filter_data = session.get('filter', {})
        year = filter_data.get('year')
        month = filter_data.get('month')

        df_guest = load_guest_data()
        if year and month:
            df_guest = total_guests(df_guest, year, month)

        month_name = month_mapping.get(month, None)

        if month_name:
            expenses_dict, monthname_year = load_dictionary_data('expenses', year, month)
            df_expenses = process_expenses(expenses_dict)
        else:
            expenses_dict, monthname_year = load_dictionary_data('expenses')
            df_expenses = process_expenses(expenses_dict)

        chart_creator = DataChartCreator(df_guest, df_expenses, year, month, mode)
        graph_json = chart_creator.create_chart()

        return render_template("data_analysis.html", graph_json=graph_json, current_module=current_module,
                               year=year, month=month, mode=mode)

routes/expenses.py
from flask import Blueprint, request, render_template, redirect, url_for, session
import json
import numpy as np
import pandas as pd
from utils.data_reading import load_guest_data, load_dictionary_data, process_expenses, total_guests, guests_by_column
from utils.helpers import store_filter_data

expenses_bp = Blueprint('expenses', __name__, template_folder='templates')


class Expenses:
    @staticmethod
    @expenses_bp.route('/')
    def show_expenses():
        """Render expense data in expenses.html template."""
        current_module = 'expenses'

        # Retrieve year and month from the session
        filter_data = session.get('filter', {})
        year = filter_data.get('year')
        month = filter_data.get('month')

        if month:
            dict_expenses, monthname_year = load_dictionary_data('expenses', year, month)
            df_expenses = process_expenses(dict_expenses)
        else:
            dict_expenses, monthname_year = load_dictionary_data('expenses')
            df_expenses = process_expenses(dict_expenses)

        # Calculate total sums for each category
        total_shopping_price = df_expenses['Shopping Price'].sum()
        total_shopping_vat = df_expenses['Shopping VAT'].sum()
        total_shopping_netto = df_expenses['Shopping Netto'].sum()

        total_apartment_price = df_expenses['Apartment Price'].sum()
        total_apartment_vat = df_expenses['Apartment VAT'].sum()
        total_apartment_netto = df_expenses['Apartment Netto'].sum()

        total_company_price = df_expenses['Company Fees Price'].sum()
        total_company_vat = df_expenses['Company Fees VAT'].sum()
        total_company_netto = df_expenses['Company Fees Netto'].sum()

        df_expenses = df_expenses.fillna('')

        # Add an index column for each category
        df_expenses['Shopping Index'] = np.where(df_expenses['Shopping Name'] != '',
                                                 np.arange(1, df_expenses['Shopping Name'].notna().sum() + 1), '')
        df_expenses['Apartment Index'] = np.where(df_expenses['Apartment Name'] != '',
                                                  np.arange(1, df_expenses['Apartment Name'].notna().sum() + 1), '')
        df_expenses['Company Fees Index'] = np.where(df_expenses['Company Fees Name'] != '',
                                                np.arange(1, df_expenses['Company Fees Name'].notna().sum() + 1), '')

        # Pass sums to the template
        return render_template(
            'expenses.html',
            tables=[df_expenses],
            current_module=current_module,
            total_shopping_price=total_shopping_price,
            total_shopping_vat=total_shopping_vat,
            total_shopping_netto=total_shopping_netto,
            total_apartment_price=total_apartment_price,
            total_apartment_vat=total_apartment_vat,
            total_apartment_netto=total_apartment_netto,
            total_company_price=total_company_price,
            total_company_vat=total_company_vat,
            total_company_netto=total_company_netto
        )

    @staticmethod
    @expenses_bp.route('/add_expense_form')
    def add_expense_form():
        """Render the Add Expense form."""
        return render_template('add_expense.html')

    @staticmethod
    @expenses_bp.route('/add_expense', methods=['POST'])
    def add_expense():
        """Add a new expense to the JSON file."""
        category = request.form['category']
        name = request.form['name']
        price = request.form['price']
        monthname = request.form['monthname']
        vat_perc = request.form['vat_perc']
        # year = request.form['year']
        year = '2024'

        monthname_year = monthname + " " + year

        # Load existing expenses
        with open('data_source/expenses.json', 'r') as file:
            expense_data = json.load(file)

        if monthname_year not in expense_data:
            expense_data[monthname_year] = {"Shopping": [], "Apartment Bills": [], "Company Fees": []}

        # Append the new expense to the Shopping category
        new_expense = {"Name": name, "Price": float(price), "VAT %": vat_perc}

        # Append the new expense to the specified category
        if category in expense_data[monthname_year]:
            expense_data[monthname_year][category].append(new_expense)

        # Save the updated data back to the JSON file
        with open('data_source/expenses.json', 'w') as file:
            json.dump(expense_data, file, indent=4)

        # Redirect back to the expenses page
        return redirect(url_for('expenses.show_expenses'))

    @staticmethod
    @expenses_bp.route('/filter_expenses', methods=['POST'])
    def filter_expenses():
        current_module = 'expenses'

        year = str(request.form['year'])  # Retrieve the selected month and year from the form
        month = str(request.form['month'])

        store_filter_data(year, month)  # Store filter data in session

        dict_expenses, monthname_year = load_dictionary_data('expenses', year, month)
        df_expenses = process_expenses(dict_expenses)

        # Calculate total sums for each category
        total_shopping_price = df_expenses['Shopping Price'].sum()
        total_shopping_vat = df_expenses['Shopping VAT'].sum()
        total_shopping_netto = df_expenses['Shopping Netto'].sum()

        total_apartment_price = df_expenses['Apartment Price'].sum()
        total_apartment_vat = df_expenses['Apartment VAT'].sum()
        total_apartment_netto = df_expenses['Apartment Netto'].sum()

        total_company_price = df_expenses['Company Fees Price'].sum()
        total_company_vat = df_expenses['Company Fees VAT'].sum()
        total_company_netto = df_expenses['Company Fees Netto'].sum()

        df_expenses = df_expenses.fillna('')

        # Add an index column for each category
        df_expenses['Shopping Index'] = np.where(df_expenses['Shopping Name'] != '',
                                                 np.arange(1, df_expenses['Shopping Name'].notna().sum() + 1), '')
        df_expenses['Apartment Index'] = np.where(df_expenses['Apartment Name'] != '',
                                                 np.arange(1, df_expenses['Apartment Name'].notna().sum() + 1), '')
        df_expenses['Company Fees Index'] = np.where(df_expenses['Company Fees Name'] != '',
                                                 np.arange(1, df_expenses['Company Fees Name'].notna().sum() + 1), '')

        # Pass sums to the template
        return render_template(
            'expenses.html',
            year=year,
            month=month,
            tables=[df_expenses],
            current_module=current_module,
            total_shopping_price=total_shopping_price,
            total_shopping_vat=total_shopping_vat,
            total_shopping_netto=total_shopping_netto,
            total_apartment_price=total_apartment_price,
            total_apartment_vat=total_apartment_vat,
            total_apartment_netto=total_apartment_netto,
            total_company_price=total_company_price,
            total_company_vat=total_company_vat,
            total_company_netto=total_company_netto
        )

routes/guests.py
from flask import Blueprint, request, render_template, redirect, url_for, session
import json
from utils.data_reading import load_guest_data, guests_by_column, total_guests
from utils.helpers import store_filter_data
import pandas as pd

guests_bp = Blueprint('guests', __name__, template_folder='templates')


class Guests:
    @staticmethod
    @guests_bp.route('/')
    def show_guests():
        """Render guest data with merged cells for total price in guests.html template."""
        current_module = 'guests'

        df_guest = load_guest_data()
        df_guest = df_guest.fillna('')

        # Convert the Date column to datetime
        df_guest['Date'] = pd.to_datetime(df_guest['Date'], format='%Y-%m-%d').dt.date
        df_guest = df_guest.sort_values(by='Date')  # Ascending order (from oldest to most recent)

        # Retrieve year and month from the session
        filter_data = session.get('filter', {})
        year = filter_data.get('year')
        month = filter_data.get('month')

        if not filter_data:
            most_recent_date = df_guest['Date'].max()
            year = most_recent_date.year
            month = f"{most_recent_date.month:02d}"
            filter_data = {'year': str(year), 'month': month}
            session['filter'] = filter_data

        if year and month:
            df_guest = total_guests(df_guest, year, month)

        df_guest['row_position_in_group'] = df_guest.groupby('Guest').cumcount()
        df_guest['group_size'] = df_guest.groupby('Guest')['Guest'].transform('size')

        return render_template('guests.html', tables=[df_guest], current_module=current_module, year=year, month=month)

    @staticmethod
    @guests_bp.route('/add_guest_form')
    def add_guest_form():
        """Render the form to add a new guest."""
        return render_template('add_guest.html')

    @staticmethod
    @guests_bp.route('/add_guest', methods=['POST'])
    def add_guest():
        """Process the new guest data, calculate fields, and update JSON file."""

        # Load the existing guest data from JSON
        with open('data_source/data.json', 'r') as file:
            guest_data = json.load(file)

        new_guest_entry = {
            "Date": request.form['date'],
            "Guest": request.form['guest'],
            "Standard": float(request.form['standard']),
            "Number of people": int(request.form['number_of_people']),
            "Offer": request.form['offer'],
            "Genius": request.form['genius'],
            "Commission %": request.form['commission']
        }

        guest_data.append(new_guest_entry)

        # Save updated data back to JSON
        with open('data_source/data.json', 'w') as file:
            json.dump(guest_data, file, indent=4)

        # Redirect to guest list page
        return redirect(url_for('guests.show_guests'))

    @staticmethod
    @guests_bp.route('/filter_guests', methods=['POST'])
    def filter_guests():
        """Filter the guest list by year and month."""
        current_module = 'guests'

        df = load_guest_data()
        df = df.fillna('')
        df = df.sort_values(by='Date')

        # Retrieve the selected month and year from the form
        year, month = str(request.form['year']), str(request.form['month'])

        # Store filter data in session
        store_filter_data(year, month)

        filtered_data = total_guests(df, year, month)

        filtered_data['row_position_in_group'] = filtered_data.groupby('Guest').cumcount()
        filtered_data['group_size'] = filtered_data.groupby('Guest')['Guest'].transform('size')

        return render_template('guests.html', year=year, month=month, tables=[filtered_data],
                               current_module=current_module)

templates/add_expense.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Expense</title>
</head>

<body>
    <h2>Add a new expense</h2>
    <form action="{{ url_for('expenses.add_expense') }}" method="POST">
        <div class="form-group">
            <label for="category">Category</label>
            <select class="form-control" id="category" name="category" required>
                <option value="Shopping">Shopping</option>
                <option value="Apartment Bills">Apartment Bills</option>
                <option value="Company Fees">Company Fees</option>
            </select>
        </div>
        <div class="form-group">
            <label for="name">Expense Name</label>
            <input type="text" class="form-control" id="name" name="name" required>
        </div>
        <div class="form-group">
            <label for="price">Price</label>
            <input type="number" step="0.01" class="form-control" id="price" name="price" required>
        </div>
        <div class="form-group">
            <label for="monthname">Month Name</label>
            <input type="text" class="form-control" id="monthname" name="monthname" required>
        </div>
        <div class="form-group">
            <label for="vat_perc">VAT %</label>
            <input type="text" class="form-control" id="vat_perc" name="vat_perc" required>
        </div>

        <button type="submit" class="btn btn-primary">Add Expense</button>
  </form>
</body>
</html>

templates/add_guest.html
<!-- add_guest.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Guest</title>
</head>

<body>
    <h2>Add a New Guest</h2>
    <form action="{{ url_for('guests.add_guest') }}" method="POST">
        <label for="date">Date:</label>
        <input type="date" id="date" name="date" required><br>

        <label for="guest">Guest Name:</label>
        <input type="text" id="guest" name="guest" required><br>

        <label for="standard">Standard Price:</label>
        <input type="number" step="0.01" id="standard" name="standard" required><br>

        <label for="number_of_people">Number of People:</label>
        <input type="number" id="number_of_people" name="number_of_people" min="1" required><br>

        <label for="offer">Offer Discount (%):</label>
        <input type="text" step="0.01" id="offer" name="offer"><br>

        <label for="genius">Genius Discount (%):</label>
        <input type="text" step="0.01" id="genius" name="genius"><br>

        <label for="commission">Commission (%):</label>
        <input type="text" step="0.01" id="commission" name="commission" required><br>

        <input type="submit" value="Add Guest">
    </form>
    <a href="{{ url_for('guests.show_guests') }}">Back to Guest List</a>
</body>
</html>

templates/data_analysis.html
{% extends "base.html" %}

{% block title %}Data Analysis{% endblock %}

{% block content %}

<head>
    <style>
        .mode-switch {
            display: flex;
            gap: 0; /* No gap to ensure buttons are joined together seamlessly */
            margin-bottom: 20px;
            justify-content: flex-end; /* Move buttons to the right side */
        }

        .toggle-button {
            border: 1px solid #ccc;
            border-right: none; /* Remove the right border for joined effect, except for the last button */
            padding: 10px 25px;
            cursor: pointer;
            background-color: #f0f0f0;
            transition: background-color 0.3s;
            color: black;
            font-weight: normal;
        }

        .toggle-button.active {
            background-color: #707070; /* Dark grey when active */
            color: white;
            font-weight: bold;
        }

        .toggle-button:hover {
            background-color: #d3d3d3; /* Light grey when hovered */
            color: black;
        }

        .toggle-button.first-child {
            border-radius: 20px 0 0 20px; /* Round left corners for first button */
        }

        .toggle-button.last-child {
            border-radius: 0 20px 20px 0; /* Round right corners for last button */
            border-right: 1px solid #ccc; /* Only add right border to the last button */
        }

    </style>
</head>

<h1>Data Analysis</h1>

<!-- Mode Switch -->
<div class="mode-switch">
    <form action="{{ url_for('data_analysis.dashboard_mode') }}" method="POST">
        <input type="hidden" name="mode" value="accounting">
        <button type="submit" id="accountingView" class="toggle-button {% if mode == 'accounting' %}active{% endif %} first-child">Accounting View</button>
    </form>
    <form action="{{ url_for('data_analysis.dashboard_mode') }}" method="POST">
        <input type="hidden" name="mode" value="reservation">
        <button type="submit" id="reservationView" class="toggle-button {% if mode == 'reservation' %}active{% endif %} last-child">Reservation View</button>
    </form>
</div>

<div id="graph"></div>

<!-- Plotly chart rendering -->
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<script type="text/javascript">
    var graphData = {{ graph_json | safe }};
    Plotly.newPlot('graph', graphData.data, graphData.layout);

    // JavaScript to handle mode switching
    function setMode(mode) {

        if (mode === 'accounting') {
            document.getElementById('accountingView').classList.add('active');
            window.location.href = "/dashboard?mode=accounting";
        } else if (mode === 'reservation') {
            document.getElementById('reservationView').classList.add('active');
            window.location.href = "/dashboard?mode=reservation";
        }
    }
</script>
{% endblock %}


templates/expenses.html
{% extends "base.html" %}

{% block title %}Expenses{% endblock %}

{% block content %}
    <script>
        function toggleForm() {
            var form = document.getElementById("expenseForm");
            form.style.display = (form.style.display === "none") ? "block" : "none";
        }
    </script>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
            font-size: 0.85rem;
            border: none !important;
        }
        th, td {
             padding: 8px;
             text-align: left;
             font-size: 0.85rem;
             border: none !important;
        }
        th {
            background-color: #f2f2f2;
        }


        .inner-container {
            border-color: #fbf895;
            box-shadow: 0 4px 15px rgba(0, 0, 0, 0.1);
            border-radius: 10px;
            overflow: hidden;  /* Ensures that child elements like table headers are contained within the rounded corners */
        }

        /* Headers*/
        .shopping-header, .apartment-header, .company-header {
            font-weight: bold;
            font-size: 1.0rem;
            text-align: center;
            padding-top: 10px;
            padding-bottom: 10px;
            background-color: white;
        }
        .shopping-header { color: #fae700; }
        .apartment-header { color: #f744c0; }
        .company-header { color: #36ea9f; }

        .shopping-header:first-child {
            border-top-left-radius: 10px;
        }
        .company-header:last-child {
            border-top-right-radius: 10px;
        }


        /* Categories */
        .shopping-category, .apartment-category, .company-category {
            padding: 8px;
            border-top: 1.2px solid black !important;
            border-bottom: 1.2px solid black !important;
        }
        .shopping-category { background-color: #fdfbb6; }
        .apartment-category { background-color: #fec7ed; }
        .company-category { background-color: #cff8e7; }


        /* Container styling for rounded boxes around each section */
        .shopping-total {
            border-top: 3px solid #fbf895 !important; /* Yellow for Shopping */
        }
        .apartment-total {
            border-top: 3px solid #ffade6 !important; /* Pink for Apartment Bills */
        }
        .company-total {
            border-top: 3px solid #b6e6d2 !important; /* Green for Company Fees */
        }

    </style>

<h1>Expenses</h1>

<div class="inner-container">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th colspan="6" class="shopping-header">Shopping</th>
                <th colspan="6" class="apartment-header">Apartment Bills</th>
                <th colspan="6" class="company-header">Company Fees</th>

            </tr>
            <tr>
                <th class="shopping-category">No.</th>
                <th class="shopping-category">Name</th>
                <th class="shopping-category">Price</th>
                <th class="shopping-category">VAT %</th>
                <th class="shopping-category">VAT</th>
                <th class="shopping-category">Netto</th>

                <th class="apartment-category">No.</th>
                <th class="apartment-category">Name</th>
                <th class="apartment-category">Price</th>
                <th class="apartment-category">VAT %</th>
                <th class="apartment-category">VAT</th>
                <th class="apartment-category">Netto</th>

                <th class="company-category">No.</th>
                <th class="company-category">Name</th>
                <th class="company-category">Price</th>
                <th class="company-category">VAT %</th>
                <th class="company-category">VAT</th>
                <th class="company-category">Netto</th>
            </tr>
        </thead>

        <tbody>
        {% for row in tables[0].to_dict(orient='records') %}
            <tr>
                <td>{{ row['Shopping Index'] }}</td>
                <td>{{ row['Shopping Name'] }}</td>
                <td>{{ row['Shopping Price'] }}</td>
                <td>{{ row['Shopping VAT %'] }}</td>
                <td>{{ row['Shopping VAT'] }}</td>
                <td>{{ row['Shopping Netto'] }}</td>

                <td>{{ row['Apartment Index'] }}</td>
                <td>{{ row['Apartment Name'] }}</td>
                <td>{{ row['Apartment Price'] }}</td>
                <td>{{ row['Apartment VAT %'] }}</td>
                <td>{{ row['Apartment VAT'] }}</td>
                <td>{{ row['Apartment Netto'] }}</td>

                <td>{{ row['Company Fees Index'] }}</td>
                <td>{{ row['Company Fees Name'] }}</td>
                <td>{{ row['Company Fees Price'] }}</td>
                <td>{{ row['Company Fees VAT %'] }}</td>
                <td>{{ row['Company Fees VAT'] }}</td>
                <td>{{ row['Company Fees Netto'] }}</td>
            </tr>
        {% endfor %}
        </tbody>

        <tfoot>
            <tr>
                <td colspan="2" style="color: #fae700;" class="shopping-total"><strong>Total</strong></td>
                <td colspan="1" class="shopping-total"><strong>{{ "{:.2f}".format(total_shopping_price) }}</strong></td>
                <td colspan="1" class="shopping-total"></td>
                <td colspan="1" class="shopping-total"><strong>{{ "{:.2f}".format(total_shopping_vat) }}</strong></td>
                <td colspan="1" class="shopping-total"><strong>{{ "{:.2f}".format(total_shopping_netto) }}</strong></td>

                <td colspan="2" style="color: #f744c0;" class="apartment-total"><strong>Total</strong></td>
                <td colspan="1" class="apartment-total"><strong>{{ "{:.2f}".format(total_apartment_price) }}</strong></td>
                <td colspan="1" class="apartment-total"></td>
                <td colspan="1" class="apartment-total"><strong>{{ "{:.2f}".format(total_apartment_vat) }}</strong></td>
                <td colspan="1" class="apartment-total"><strong>{{ "{:.2f}".format(total_apartment_netto) }}</strong></td>

                <td colspan="2" style="color: #36ea9f;" class="company-total"><strong>Total</strong></td>
                <td colspan="1" class="company-total"><strong>{{ "{:.2f}".format(total_company_price) }}</strong></td>
                <td colspan="1" class="company-total"></td>
                <td colspan="1" class="company-total"><strong>{{ "{:.2f}".format(total_company_vat) }}</strong>  </td>
                <td colspan="1" class="company-total"><strong>{{ "{:.2f}".format(total_company_netto) }}</strong></td>
            </tr>
        </tfoot>
    </table>
</div>
{% endblock %}